### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by jeffbaumes** [XDATA-Year-3/geoapp#93]
When following notes.txt I get

```
(env)jeff@firebrick:/code/geoapp/env (master) $ pip install -r ../requirements.txt
Traceback (most recent call last):
  File "/code/geoapp/env/bin/pip", line 7, in <module>
    from pip import main
  File "/code/geoapp/env/lib/python2.7/site-packages/pip/__init__.py", line 13, in <module>
    from pip.commands import commands, get_summaries, get_similar_commands
  File "/code/geoapp/env/lib/python2.7/site-packages/pip/commands/__init__.py", line 6, in <module>
    from pip.commands.bundle import BundleCommand
  File "/code/geoapp/env/lib/python2.7/site-packages/pip/commands/bundle.py", line 6, in <module>
    from pip.commands.install import InstallCommand
  File "/code/geoapp/env/lib/python2.7/site-packages/pip/commands/install.py", line 5, in <module>
    from pip.req import InstallRequirement, RequirementSet, parse_requirements
  File "/code/geoapp/env/lib/python2.7/site-packages/pip/req/__init__.py", line 3, in <module>
    from .req_install import InstallRequirement
  File "/code/geoapp/env/lib/python2.7/site-packages/pip/req/req_install.py", line 31, in <module>
    from pip.utils import (
  File "/code/geoapp/env/lib/python2.7/site-packages/pip/utils/__init__.py", line 59, in <module>
    def rmtree(dir, ignore_errors=False):
  File "/code/geoapp/env/lib/python2.7/site-packages/pip/_vendor/retrying.py", line 47, in wrap
    @six.wraps(f)
AttributeError: 'module' object has no attribute 'wraps'
```

**Comment by jeffbaumes** [comment]
Was a conflict with an older virtualenv setup on my machine.
